### ISSUE TITLE
Add Tayda carts links and/or csvs to each module

### ISSUE THREAD

**Issue by rl2939** [QuinnFreedman/modular#48]
Right now, if a user wants to build a module, they have to source all of the parts by hand. It would be convenient if most* of the parts could be obtained in one place.

Two such options to do so are Mouser's "projectManager" (a url that contains the list of items to order) and Tayda's "Quick Order" CSV (a csv that you can upload to Tayda' auto order system to get an list of item need to buy in one place.)

An example of someone doing this can be found [here](https://github.com/musicdevghost/eurorack/tree/main/TOM%20YUM%20-%20VCO) (Scroll to "Build Instructions")

* excluding microcontrollers like the Arduino Nano, etc

**Comment by QuinnFreedman** [comment]
I hadn't done this because I was having trouble with availability. The big electronics sellers seemed to not stock a lot of the synth-specific parts that I got from Thonk.

I didn't know about Tayda, though. It looks like they have a good selection and very good prices. I'll start adding Tayda carts to each module, and just make note of the few things they don't have
