### ISSUE TITLE
RNG: negative loop length values behave the same as positive loop length values

### ISSUE THREAD

**Issue by roagm** [QuinnFreedman/modular#56]
According to the manual, negative loop length values should cause the output CV sequence to alternate direction. With current firmware, negative loop length values output exactly the same CV sequence as their positive counterparts. 

For example, setting the loop length to 8 will output exactly the same CV sequence as setting the loop length to -8

**Comment by QuinnFreedman** [comment]
Thanks for testing the module out. It seems like this one was less well tested than I thought! I'll take a look at this today

**Comment by QuinnFreedman** [comment]
This should be fixed now. New firmware should be live to download.

The current version uses a "pendulum" mode to reverse direction so that the end steps are not repeated. A "pingpong" version is also available that plays the full length sequence forwards and backward, repeating the first and last step. It can be selected before compiling firmware. I'm open to changing what the default is

**Comment by roagm** [comment]
I can confirm that negative loop length values now work as described on the manual.

I don't really have a preference regarding the "pendulum" or "pingpong" modes, so I think the current default is fine.
